pref: update installer

diff --git a/install b/install
--- a/install
+++ b/install
@@ -45,6 +45,10 @@ initial_checks() {
   fi
 }
 
+is_installed() {
+  pacman -Qq "$1" >/dev/null 2>&1
+}
+
 welcome() {
   clear
   logo "Welcome $USER"
@@ -209,38 +213,19 @@ install_paru() {
 
 install_dependencies() {
   clear
-  logo "Installing needed packages..."
+  logo "Installing needed packages from official repositories..."
   sleep 2
 
-  is_installed() {
-    pacman -Qq "$1" >/dev/null 2>&1
-  }
-
   local dependencies=(
-    alacritty base-devel bat brightnessctl bspwm clipcat dunst eza feh thunar
+    alacritty base-devel bat brightnessctl bspwm clipcat dunst eza feh fzf thunar
     tumbler firefox git imagemagick jq jgmenu kitty libwebp maim
     mpc mpd mpv neovim ncmpcpp npm pamixer pacman-contrib papirus-icon-theme
     picom playerctl polybar polkit-gnome python-gobject redshift rofi rustup
     sxhkd tmux xclip xdg-user-dirs xdo xdotool xsettingsd xorg-xdpyinfo
     xorg-xkill xorg-xprop xorg-xrandr xorg-xsetroot xorg-xwininfo yazi zsh
     ttf-inconsolata ttf-jetbrains-mono ttf-jetbrains-mono-nerd ttf-terminus-nerd
-    ttf-ubuntu-mono-nerd ueberzugpp webp-pixbuf-loader tdrop eww-git
-    i3lock-color gh0stzk-gtk-themes gh0stzk-cursor-qogirr
-    gh0stzk-icons-beautyline gh0stzk-icons-candy gh0stzk-icons-catppuccin-mocha
-    gh0stzk-icons-dracula gh0stzk-icons-glassy gh0stzk-icons-gruvbox-plus-dark
-    gh0stzk-icons-hack gh0stzk-icons-luv gh0stzk-icons-sweet-rainbow
-    gh0stzk-icons-tokyo-night gh0stzk-icons-vimix-white gh0stzk-icons-zafiro
-    gh0stzk-icons-zafiro-purple
+    ttf-ubuntu-mono-nerd webp-pixbuf-loader
   )
-
-  # Handle ueberzug/ueberzugpp conflict
-  if is_installed "ueberzug"; then
-    echo -e "\n${BLD}${CYE}Removing conflicting ueberzug package...${CNC}\n"
-    sudo pacman -Rns --noconfirm ueberzug >>"$ERROR_LOG" 2>&1 || {
-      log_error "Failed to remove ueberzug"
-      echo -e "${BLD}${CRE}Error removing ueberzug! Check logs${CNC}\n\n"
-    }
-  fi
 
   echo -e "${BLD}${CBL}Checking for required packages...${CNC}\n"
   sleep 2
@@ -285,16 +270,120 @@ install_dependencies() {
   sleep 3
 }
 
-install_aur_dependencies() {
+install_gh0stzk_dependencies() {
   clear
-  logo "Installing AUR dependencies."
+  logo "Installing needed packages from gh0stzk repository..."
   sleep 2
 
-  is_installed() {
-    pacman -Qq "$1" >/dev/null 2>&1
-  }
+  local gh0stzk_dependencies=(
+    gh0stzk-gtk-themes gh0stzk-cursor-qogirr gh0stzk-icons-beautyline
+    gh0stzk-icons-candy gh0stzk-icons-catppuccin-mocha gh0stzk-icons-dracula
+    gh0stzk-icons-glassy gh0stzk-icons-gruvbox-plus-dark gh0stzk-icons-hack
+    gh0stzk-icons-luv gh0stzk-icons-sweet-rainbow gh0stzk-icons-tokyo-night
+    gh0stzk-icons-vimix-white gh0stzk-icons-zafiro gh0stzk-icons-zafiro-purple
+  )
 
-  local aur_apps=(xqp xwinwrap-0.9-bin ttf-maple)
+  echo -e "\n${BLD}${CBL}Checking for required packages...${CNC}\n"
+  sleep 2
+
+  local missing_gh0stzk_pkgs=()
+  for pkg in "${gh0stzk_dependencies[@]}"; do
+    if ! is_installed "$pkg"; then
+      missing_gh0stzk_pkgs+=("$pkg")
+      echo -e " ${BLD}${CYE}${pkg} ${CRE}not installed${CNC}"
+    else
+      echo -e "${BLD}${CGR}${pkg} ${CBL}already installed${CNC}"
+    fi
+  done
+
+  if ((${#missing_gh0stzk_pkgs[@]} > 0)); then
+    echo -e "\n${BLD}${CYE}Installing ${#missing_gh0stzk_pkgs[@]} packages...${CNC}\n"
+
+    if sudo pacman -S --noconfirm --needed "${missing_gh0stzk_pkgs[@]}" >>"$ERROR_LOG" 2>&1; then
+      local failed_gh0stzk_pkgs=()
+      for pkg in "${missing_gh0stzk_pkgs[@]}"; do
+        if ! is_installed "$pkg"; then
+          failed_gh0stzk_pkgs+=("$pkg")
+          log_error "Failed to install: $pkg"
+        fi
+      done
+
+      if ((${#failed_gh0stzk_pkgs[@]} == 0)); then
+        echo -e "${BLD}${CGR}All packages installed successfully!${CNC}\n\n"
+      else
+        echo -e "${BLD}${CRE}Failed to install ${#failed_gh0stzk_pkgs[@]} packages:${CNC}\n"
+        echo -e "  ${BLD}${CYE}${failed_gh0stzk_pkgs[*]}${CNC}\n\n"
+      fi
+    else
+      log_error "Critical error during batch installation"
+      echo -e "${BLD}${CRE}Installation failed! Check log for details${CNC}\n"
+      return 1
+    fi
+  else
+    echo -e "\n${BLD}${CGR}All dependencies are already installed!${CNC}"
+  fi
+
+  sleep 3
+}
+
+install_chaotic_dependencies() {
+  clear
+  logo "Installing needed packages from chaotic repository..."
+  sleep 2
+
+  local chaotic_dependencies=(
+    paru eww-git i3lock-color fzf-tab-git
+  )
+
+  echo -e "\n${BLD}${CBL}Checking for required packages...${CNC}\n"
+  sleep 2
+
+  local missing_chaotic_pkgs=()
+  for pkg in "${chaotic_dependencies[@]}"; do
+    if ! is_installed "$pkg"; then
+      missing_chaotic_pkgs+=("$pkg")
+      echo -e " ${BLD}${CYE}${pkg} ${CRE}not installed${CNC}"
+    else
+      echo -e "${BLD}${CGR}${pkg} ${CBL}already installed${CNC}"
+    fi
+  done
+
+  if ((${#missing_chaotic_pkgs[@]} > 0)); then
+    echo -e "\n${BLD}${CYE}Installing ${#missing_chaotic_pkgs[@]} packages...${CNC}\n"
+
+    if sudo pacman -S --noconfirm --needed "${missing_chaotic_pkgs[@]}" >>"$ERROR_LOG" 2>&1; then
+      local failed_chaotic_pkgs=()
+      for pkg in "${missing_chaotic_pkgs[@]}"; do
+        if ! is_installed "$pkg"; then
+          failed_chaotic_pkgs+=("$pkg")
+          log_error "Failed to install: $pkg"
+        fi
+      done
+
+      if ((${#failed_chaotic_pkgs[@]} == 0)); then
+        echo -e "${BLD}${CGR}All packages installed successfully!${CNC}\n\n"
+      else
+        echo -e "${BLD}${CRE}Failed to install ${#failed_chaotic_pkgs[@]} packages:${CNC}\n"
+        echo -e "  ${BLD}${CYE}${failed_chaotic_pkgs[*]}${CNC}\n\n"
+      fi
+    else
+      log_error "Critical error during batch installation"
+      echo -e "${BLD}${CRE}Installation failed! Check log for details${CNC}\n"
+      return 1
+    fi
+  else
+    echo -e "\n${BLD}${CGR}All dependencies are already installed!${CNC}"
+  fi
+
+  sleep 3
+}
+
+install_aur_dependencies() {
+  clear
+  logo "Installing AUR dependencies..."
+  sleep 2
+
+  local aur_apps=(xqp xwinwrap-0.9-bin)
 
   echo -e "${BLD}${CBL}Checking for required AUR packages...${CNC}\n"
   sleep 2
