Upgrade install script

diff --git a/.dotfiles/xenon/install b/.dotfiles/xenon/install
--- a/.dotfiles/xenon/install
+++ b/.dotfiles/xenon/install
@@ -10,14 +10,14 @@ CNC=$(tput sgr0)
 backup_folder=~/.backup
 date=$(date +%Y%m%d-%H%M%S)
 
-logo () {
-  local text="${1:?}"
-  printf '%s [%s%s %s%s %s]%s\n' "${CRE}" "${CNC}" "${CYE}" "${text}" "${CNC}" "${CRE}" "${CNC}"
+logo() {
+	local text="${1:?}"
+	printf '%s [%s%s %s%s %s]%s\n' "${CRE}" "${CNC}" "${CYE}" "${text}" "${CNC}" "${CRE}" "${CNC}"
 }
 
 if [ "$(id -u)" = 0 ]; then
-  echo "This script cannot be run as root user!"
-  exit 1
+	echo "This script cannot be run as root user!"
+	exit 1
 fi
 
 # Welcome
@@ -36,43 +36,43 @@ it only copies files from my repository to your HOME directory.%s\n\n' "${BLD}" 
 
 while true; do
 	read -rp " Do you want to continue? [y/N]: " yn
-		case $yn in
-			[Yy]* ) break;;
-			[Nn]* ) exit;;
-			* ) printf " Error: Please enter 'y' or 'n'\n\n";;
-		esac
-    done
+	case $yn in
+	[Yy]*) break ;;
+	[Nn]*) exit ;;
+	*) printf " Error: Please enter 'y' or 'n'\n\n" ;;
+	esac
+done
 clear
 
 # Install packages
 
 logo "Install needed packages"
 
-dependencias=(base-devel rustup pacman-contrib bspwm polybar sxhkd \
-			  alacritty brightnessctl dunst rofi lsd \
-			  jq polkit-gnome git playerctl mpd \
-			  ncmpcpp geany ranger mpc picom xdotool \
-			  feh ueberzug maim pamixer libwebp xdg-user-dirs \
-			  webp-pixbuf-loader xorg-xprop xorg-xkill physlock papirus-icon-theme \
-			  ttf-jetbrains-mono ttf-jetbrains-mono-nerd ttf-terminus-nerd ttf-inconsolata ttf-joypixels \
-			  zsh zsh-autosuggestions zsh-history-substring-search zsh-syntax-highlighting xorg-xsetroot xorg-xwininfo xorg-xrandr)
+dependencias=(base-devel rustup pacman-contrib bspwm polybar sxhkd
+	alacritty brightnessctl dunst rofi lsd
+	jq polkit-gnome git playerctl mpd python-pip python-pynvim nodejs npm
+	ncmpcpp geany ranger mpc picom xdotool
+	feh ueberzug maim pamixer libwebp xdg-user-dirs
+	webp-pixbuf-loader xorg-xprop xorg-xkill physlock papirus-icon-theme
+	ttf-jetbrains-mono ttf-jetbrains-mono-nerd ttf-terminus-nerd ttf-inconsolata ttf-joypixels
+	zsh zsh-autosuggestions zsh-history-substring-search zsh-syntax-highlighting xorg-xsetroot xorg-xwininfo xorg-xrandr)
 
 is_installed() {
-  pacman -Qi "$1" &> /dev/null
-  return $?
+	pacman -Qi "$1" &>/dev/null
+	return $?
 }
 
 printf "%s%sChecking for required packages...%s\n" "${BLD}" "${CBL}" "${CNC}"
-for paquete in "${dependencias[@]}"
-do
-  if ! is_installed "$paquete"; then
-    sudo pacman -S "$paquete" --noconfirm
-    printf "\n"
-  else
-    printf '%s%s is already installed!%s\n' "${CGR}" "$paquete" "${CNC}"
-    sleep 1
-  fi
+for paquete in "${dependencias[@]}"; do
+	if ! is_installed "$paquete"; then
+		sudo pacman -S "$paquete" --noconfirm
+		printf "\n"
+	else
+		printf '%s%s is already installed!%s\n' "${CGR}" "$paquete" "${CNC}"
+		sleep 1
+	fi
 done
+sudo npm install -g neovim
 sleep 3
 clear
 
@@ -85,7 +85,7 @@ if [ ! -e $HOME/.config/user-dirs.dirs ]; then
 else
 	echo "user-dirs.dirs is already exists!"
 fi
-sleep 2 
+sleep 2
 clear
 
 # Clone the Rice
@@ -105,34 +105,34 @@ printf "Backup files will be stored in %s%s%s/.backup%s \n\n" "${BLD}" "${CRE}" 
 sleep 10
 
 if [ ! -d "$backup_folder" ]; then
-  mkdir -p "$backup_folder"
+	mkdir -p "$backup_folder"
 fi
 
 for folder in bspwm alacritty picom rofi eww sxhkd dunst polybar ncmpcpp nvim ranger zsh mpd yay; do
-  if [ -d "$HOME/.config/$folder" ]; then
-    mv "$HOME/.config/$folder" "$backup_folder/${folder}_$date"
-    echo "$folder folder backed up successfully at $backup_folder/${folder}_$date"
-  else
-    echo "The folder $folder does not exist in $HOME/.config/"
-  fi
+	if [ -d "$HOME/.config/$folder" ]; then
+		mv "$HOME/.config/$folder" "$backup_folder/${folder}_$date"
+		echo "$folder folder backed up successfully at $backup_folder/${folder}_$date"
+	else
+		echo "The folder $folder does not exist in $HOME/.config/"
+	fi
 done
 
 for folder in chrome; do
-  if [ -d "$HOME"/.mozilla/firefox/*.default-release/$folder ]; then
-    mv "$HOME"/.mozilla/firefox/*.default-release/$folder "$backup_folder"/${folder}_$date
-    echo "$folder folder backed up successfully at $backup_folder/${folder}_$date"
-  else
-    echo "The folder $folder does not exist in $HOME/.mozilla/firefox/"
-  fi
+	if [ -d "$HOME"/.mozilla/firefox/*.default-release/$folder ]; then
+		mv "$HOME"/.mozilla/firefox/*.default-release/$folder "$backup_folder"/${folder}_$date
+		echo "$folder folder backed up successfully at $backup_folder/${folder}_$date"
+	else
+		echo "The folder $folder does not exist in $HOME/.mozilla/firefox/"
+	fi
 done
 
 for file in user.js; do
-  if [ -e "$HOME"/.mozilla/firefox/*.default-release/$file ]; then
-    mv "$HOME"/.mozilla/firefox/*.default-release/$file "$backup_folder"/${file}_$date
-    echo "$file file backed up successfully at $backup_folder/${file}_$date"
-  else
-    echo "The file $file does not exist in $HOME/.mozilla/firefox/"
-  fi
+	if [ -e "$HOME"/.mozilla/firefox/*.default-release/$file ]; then
+		mv "$HOME"/.mozilla/firefox/*.default-release/$file "$backup_folder"/${file}_$date
+		echo "$file file backed up successfully at $backup_folder/${file}_$date"
+	else
+		echo "The file $file does not exist in $HOME/.mozilla/firefox/"
+	fi
 done
 
 [ -f ~/.zshrc ] && mv ~/.zshrc ~/.backup/.zshrc-backup-"$(date +%Y.%m.%d-%H.%M.%S)"
@@ -152,69 +152,69 @@ printf "Copying files to respective directories...\n"
 [ ! -d ~/.local/share/asciiart ] && mkdir -p ~/.local/share/asciiart
 
 for archivos in ~/1llusion/.dotfiles/xenon/config/*; do
-  cp -R "${archivos}" ~/.config/
-  if [ $? -eq 0 ]; then
-	printf "%s%s%s folder copied succesfully!%s\n" "${BLD}" "${CGR}" "${archivos}" "${CNC}"
-	sleep 1
-  else
-	printf "%s%s%s failed to been copied, you must copy it manually!%s\n" "${BLD}" "${CRE}" "${archivos}" "${CNC}"
-	sleep 1
-  fi
+	cp -R "${archivos}" ~/.config/
+	if [ $? -eq 0 ]; then
+		printf "%s%s%s folder copied succesfully!%s\n" "${BLD}" "${CGR}" "${archivos}" "${CNC}"
+		sleep 1
+	else
+		printf "%s%s%s failed to been copied, you must copy it manually!%s\n" "${BLD}" "${CRE}" "${archivos}" "${CNC}"
+		sleep 1
+	fi
 done
 
 for archivos in ~/1llusion/.dotfiles/xenon/misc/bin/*; do
-  cp -R "${archivos}" ~/.local/bin/
-  if [ $? -eq 0 ]; then
-	printf "%s%s%s file copied succesfully!%s\n" "${BLD}" "${CGR}" "${archivos}" "${CNC}"
-	sleep 1
-  else
-	printf "%s%s%s failed to been copied, you must copy it manually!%s\n" "${BLD}" "${CRE}" "${archivos}" "${CNC}"
-	sleep 1
-  fi
+	cp -R "${archivos}" ~/.local/bin/
+	if [ $? -eq 0 ]; then
+		printf "%s%s%s file copied succesfully!%s\n" "${BLD}" "${CGR}" "${archivos}" "${CNC}"
+		sleep 1
+	else
+		printf "%s%s%s failed to been copied, you must copy it manually!%s\n" "${BLD}" "${CRE}" "${archivos}" "${CNC}"
+		sleep 1
+	fi
 done
 
 for archivos in ~/1llusion/.dotfiles/xenon/misc/applications/*; do
-  cp -R "${archivos}" ~/.local/share/applications/
-  if [ $? -eq 0 ]; then
-	printf "%s%s%s file copied succesfully!%s\n" "${BLD}" "${CGR}" "${archivos}" "${CNC}"
-	sleep 1
-  else
-	printf "%s%s%s failed to been copied, you must copy it manually!%s\n" "${BLD}" "${CRE}" "${archivos}" "${CNC}"
-	sleep 1
-  fi
+	cp -R "${archivos}" ~/.local/share/applications/
+	if [ $? -eq 0 ]; then
+		printf "%s%s%s file copied succesfully!%s\n" "${BLD}" "${CGR}" "${archivos}" "${CNC}"
+		sleep 1
+	else
+		printf "%s%s%s failed to been copied, you must copy it manually!%s\n" "${BLD}" "${CRE}" "${archivos}" "${CNC}"
+		sleep 1
+	fi
 done
 
 for archivos in ~/1llusion/.dotfiles/xenon/misc/fonts/*; do
-  cp -R "${archivos}" ~/.local/share/fonts/
-  if [ $? -eq 0 ]; then
-	printf "%s%s%s copied succesfully!%s\n" "${BLD}" "${CGR}" "${archivos}" "${CNC}"
-	sleep 1
-  else
-	printf "%s%s%s failed to been copied, you must copy it manually!%s\n" "${BLD}" "${CRE}" "${archivos}" "${CNC}"
-	sleep 1
-  fi
+	cp -R "${archivos}" ~/.local/share/fonts/
+	if [ $? -eq 0 ]; then
+		printf "%s%s%s copied succesfully!%s\n" "${BLD}" "${CGR}" "${archivos}" "${CNC}"
+		sleep 1
+	else
+		printf "%s%s%s failed to been copied, you must copy it manually!%s\n" "${BLD}" "${CRE}" "${archivos}" "${CNC}"
+		sleep 1
+	fi
 done
 
 for archivos in ~/1llusion/.dotfiles/xenon/misc/asciiart/*; do
-  cp -R "${archivos}" ~/.local/share/asciiart/
-  if [ $? -eq 0 ]; then
-	printf "%s%s%s file copied succesfully!%s\n" "${BLD}" "${CGR}" "${archivos}" "${CNC}"
-	sleep 1
-  else
-	printf "%s%s%s failed to been copied, you must copy it manually!%s\n" "${BLD}" "${CRE}" "${archivos}" "${CNC}"
-	sleep 1
-  fi
+	cp -R "${archivos}" ~/.local/share/asciiart/
+	if [ $? -eq 0 ]; then
+		printf "%s%s%s file copied succesfully!%s\n" "${BLD}" "${CGR}" "${archivos}" "${CNC}"
+		sleep 1
+	else
+		printf "%s%s%s failed to been copied, you must copy it manually!%s\n" "${BLD}" "${CRE}" "${archivos}" "${CNC}"
+		sleep 1
+	fi
 done
 
 for archivos in ~/1llusion/.dotfiles/xenon/misc/firefox/*; do
-  cp -R "${archivos}" ~/.mozilla/firefox/*.default-release/
-  if [ $? -eq 0 ]; then
-	printf "%s%s%s folder copied succesfully!%s\n" "${BLD}" "${CGR}" "${archivos}" "${CNC}"
-	sleep 1
-  else
-	printf "%s%s%s failed to been copied, you must copy it manually!%s\n" "${BLD}" "${CRE}" "${archivos}" "${CNC}"
-	sleep 1
-  fi
+	cp -R "${archivos}" ~/.mozilla/firefox/*.default-release/
+	if [ $? -eq 0 ]; then
+		printf "%s%s%s folder copied succesfully!%s\n" "${BLD}" "${CGR}" "${archivos}" "${CNC}"
+		sleep 1
+	else
+		printf "%s%s%s failed to been copied, you must copy it manually!%s\n" "${BLD}" "${CRE}" "${archivos}" "${CNC}"
+		sleep 1
+	fi
 done
 
 # cp -f "$HOME"/1llusion/.dotfiles/xenon/home/.zshrc "$HOME"
@@ -227,18 +227,18 @@ sleep 3
 logo "Install yay & eww"
 
 if ! command -v yay >/dev/null 2>&1; then
-    printf "%s%sInstalling yay...%s\n" "${BLD}" "${CBL}" "${CNC}"
-    git clone https://aur.archlinux.org/yay-bin.git
-    cd yay-bin
-    makepkg -si
-    yay -Y --gendb
-    yay -Y --devel --save
-    yay -Syu --devel
+	printf "%s%sInstalling yay...%s\n" "${BLD}" "${CBL}" "${CNC}"
+	git clone https://aur.archlinux.org/yay-bin.git
+	cd yay-bin
+	makepkg -si
+	yay -Y --gendb
+	yay -Y --devel --save
+	yay -Syu --devel
 else
-    printf "\n%s%syay is already installed!%s\n" "${BLD}" "${CGR}" "${CNC}"
+	printf "\n%s%syay is already installed!%s\n" "${BLD}" "${CGR}" "${CNC}"
 fi
 
-if ! command -v eww >/dev/null 2>&1; then 
+if ! command -v eww >/dev/null 2>&1; then
 	printf "\n%s%sInstalling eww... This could take 10 mins or more!%s\n" "${BLD}" "${CBL}" "${CNC}"
 	yay -S eww --noconfirm
 	rm -rf {.cargo,.rustup}
@@ -271,10 +271,10 @@ printf "%s%sIf your shell is not zsh, will be changed now.\n
 Your root password is needed to make the change.\n\n
 After that is important for you to reboot!\n %s\n" "${BLD}" "${CYE}" "${CNC}"
 if [[ $SHELL != "/usr/bin/zsh" ]]; then
-  echo "Changing shell to zsh... Your root password is needed:"
-  chsh -s /usr/bin/zsh
+	echo "Changing shell to zsh... Your root password is needed:"
+	chsh -s /usr/bin/zsh
 else
-  printf "%s%sYour shell is already change to zsh successfully!\n
+	printf "%s%sYour shell is already change to zsh successfully!\n
 Good bye! Installation finished, now reboot your computer and enjoy!%s\n" "${BLD}" "${CGR}" "${CNC}"
-  zsh
+	zsh
 fi
